### ISSUE TITLE
Broken AsciiMath rendering

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#11]
The formula is:
```
D[s_(i-j-1) , ..., s_(i-2)][s_(i-1)] = 0
```

On http://asciimath.org/ , it renders correctly.
![screen shot 2019-01-07 at 2 31 25 pm](https://user-images.githubusercontent.com/11865/50752358-ef3b3d80-1288-11e9-9874-4e21c13c58b6.png)

In Metanorma, it's broken:

```adoc
stem:[D[s_(i-j-1) , ..., s_(i-2)][s_(i-1)] = 0]
```
![screen shot 2019-01-07 at 2 31 49 pm](https://user-images.githubusercontent.com/11865/50752373-fe21f000-1288-11e9-9183-35246db2f4ae.png)

Clearly someone used broken RegExes to parse -- the `stem:[]` block closed with the earlier `]` bracket.

**Comment by ronaldtse** [comment]
So apparently there is AsciiMath (ASCIIMath.org), and there is the "Asciidoctor's implementation" of AsciiMath. The latter is apparently implemented in a simplistic way, and maybe that's what has been causing us long build times.

1. There is no "official" ASCII-Math syntax.
2. Maybe there should be one.
3. Maybe we need a better Ruby implementation to convert AsciiMath into MathML.

**Comment by ronaldtse** [comment]
Or in Rust (https://andre.arko.net/2018/10/25/parsing-logs-230x-faster-with-rust/)

**Comment by opoudjis** [comment]
Square brackets within stem macros have to be escaped with backslash, Dan Allen himself commented so in a ticket. The Asciidoc AsciiMath implementation has a lot of faults, but that particular issue is a host Asciidoc issue across all their macros. It is to do with the Asciidoc preprocessor being regex-driven and not parser-driven, unlike Asciidoc AsciiMath.

**Comment by opoudjis** [comment]
The broader issues of AsciiMath efficiency and formalisation range must broader than this issue, and any further discussion belongs in a new issue...

**Comment by opoudjis** [comment]
I just globally replaced all instances in the doc.
