### ISSUE TITLE
"Normative References" should use alphabetical listing, not numerical listing

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#14]
Generated:

![screen shot 2019-01-07 at 8 13 49 pm](https://user-images.githubusercontent.com/11865/50767694-c03cc000-12b8-11e9-9bf5-a0fc64fca55d.png)

Original:

![screen shot 2019-01-07 at 8 14 39 pm](https://user-images.githubusercontent.com/11865/50767728-de0a2500-12b8-11e9-8de8-eaa7534af5b2.png)

**Comment by opoudjis** [comment]
You are not getting a table differentiating URLs and Names—a structure that after all does not apply whatsoever to 116. All I've done is made it treat the references like ISO Normative References and not like ISO Bibliography, which gets rid of the numeric references.
