### ISSUE TITLE
Glossary and Acronyms should bold "terms"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#15]
Generated:
![screen shot 2019-01-07 at 8 16 18 pm](https://user-images.githubusercontent.com/11865/50767793-27f30b00-12b9-11e9-9eec-46c64a292a9d.png)

Original:
![screen shot 2019-01-07 at 8 16 12 pm](https://user-images.githubusercontent.com/11865/50767790-26294780-12b9-11e9-9543-fa61d49feb0d.png)

**Comment by ronaldtse** [comment]
Acronyms.

Generated:
![screen shot 2019-01-07 at 8 17 33 pm](https://user-images.githubusercontent.com/11865/50767818-4527d980-12b9-11e9-94cb-5478495e0752.png)

Original:
![screen shot 2019-01-07 at 8 17 43 pm](https://user-images.githubusercontent.com/11865/50767825-4a852400-12b9-11e9-9201-c6185b181df9.png)

**Comment by opoudjis** [comment]
Implemented with "glossary" style attribute on definition lists.
