### ISSUE TITLE
Table of Contents should be split into "Content" vs "Appendices"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#19]
Left original, right generated.

Appendixes should be in separate ToC after content ToC.

![screen shot 2019-01-07 at 8 55 13 pm](https://user-images.githubusercontent.com/11865/50769447-f0875d00-12be-11e9-8913-8e91106a857e.png)

**Comment by opoudjis** [comment]
To be addressed by creating distinct list of heading styles in Word output, AppendixH1 ... AppendixH6, and basing index on those.

**Comment by opoudjis** [comment]
Done.
