### ISSUE TITLE
New first-level sections should be shown on new page

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#22]
Left original, right generated.

As title.

![screen shot 2019-01-07 at 9 03 47 pm](https://user-images.githubusercontent.com/11865/50769693-bcf90280-12bf-11e9-8b15-b491ace19804.png)

**Comment by ronaldtse** [comment]
Header styling is correct, but the new page break is still pending.

**Comment by opoudjis** [comment]
> And some Appendices are ending with a "black block", I assume it is an empty paragraph that is using the "HEADER" style.

If only it was that simple. The page break `<br/>` is between divs, and Word HTML CSS expects everything to be contained within a div or p. As a result, that br is getting its styling from the following h1 within the following div (!).

To avoid this, any br in Word HTML need to be within a paragraph: they will then take the styling of the paragraph, which is Normal, and not the styling of the following paragraph.

**Comment by opoudjis** [comment]
Word CSS is not permitting h1 page break attribute to be overwritten in more specific h1 classes (so default page break, but not for Intro/Abstract titles). As a result, I have to create a  NormalTitle class as a fallback for h1, and assign the page break there.

**Comment by ronaldtse** [comment]
Aha, that's why I couldn't get it working. Kudos @opoudjis !
