### ISSUE TITLE
Pseudocode block missing caption

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#25]
Pseudocode block missing caption.

```adoc
.Pseudo-code of the Fisher-Yates Shuffle
[pseudocode]
====
Input:: stem:[S = (s_1 , ... , s_L)]

Output:: Shuffled stem:[S = (s_1 , ... , s_L)]

. *for* stem:[i] *from* stem:[L] *downto* stem:[1] *do*

.. Generate a random integer stem:[j] such that stem:[1 <= j <= i].

.. Swap stem:[s_j] and stem:[s_i]
====
```

Original:

![screen shot 2019-01-07 at 11 23 13 pm](https://user-images.githubusercontent.com/11865/50797787-eb52fe00-1310-11e9-9b6c-c8d05a5b1c59.png)

Generated:

![screen shot 2019-01-07 at 11 23 10 pm](https://user-images.githubusercontent.com/11865/50776178-49f98700-12d3-11e9-887a-8cac6e817260.png)

**Comment by opoudjis** [comment]
This means that these pseudocode instances are not considered examples, but figures. 

However, this also means that only those pseudocode instances that are captioned are being counted in the counts of figures. That will not stand. All figures will be counted consecutively.

**Comment by ronaldtse** [comment]
@opoudjis this is an interesting discussion. In fact, I would rather consider pseudocode instances not examples or figures, but actual requirements. It *could* be an _example_ or a _requirement_, that is. 

The same applies to source code. It *could* be an example, or an actual requirement. The context we were given indicates that they don't need to be called "Figure".

**Comment by opoudjis** [comment]
... Except that we have instances where pseudocode was explicitly labelled as "Figure n", which means they *did* count it as a figure there.

This is something they will need to think about and clean up. And I am quite happy for this kind of implementation to rub their noses in the issue they've left pending, as it were. I will not be changing the handling of pseudocode without explicit instruction from them: NIST needs to think about their markup if they are to depart from Word.
