### ISSUE TITLE
List block content indenting after STEM block

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#27]
The line after the STEM block should stay indented in the list.

Generated:
![screen shot 2019-01-08 at 6 56 03 am](https://user-images.githubusercontent.com/11865/50798198-8698a300-1312-11e9-9909-64521fbb863b.png)

Original:
![screen shot 2019-01-08 at 6 57 09 am](https://user-images.githubusercontent.com/11865/50798227-9f08bd80-1312-11e9-82e1-ae5a258154d9.png)

````
. Construct the sequence stem:[S' = ( s'_1 , ... , s'_(L - 1) )], where
+
[stem]
++++
s'_i = {(- 1, if s_i > s_(i + 1)),( + 1, if s_i <= s_(i + 1)):}
++++
+
for stem:[i = 1, ..., L - 1].
````

**Comment by opoudjis** [comment]
Known issue https://github.com/riboseinc/isodoc/issues/73: this simply cannot be done in Word HTML.

And in fact, look carefully at the source: the only way the Word document has done it in the first place was by inserting a tab before the second line, or by changing the indentation of the subsequent paragraph.

Fixing this would require revisiting https://github.com/riboseinc/isodoc/issues/73, and maybe creating a brand new style for continuation paragraphs of a list, that matches the indentation of the  first paragraph. I will not be working further on this this week.

**Comment by ronaldtse** [comment]
Darn. Didn't know this. Let's postpone this to a more agreeable time.

**Comment by opoudjis** [comment]
https://github.com/riboseinc/isodoc/issues/73 has been solved after all.

**Comment by opoudjis** [comment]
And indeed, now the "for stem:[i = 1, ..., L - 1]." indents correctly.

The problem now is that the Math expression does *not* indent correctly in ISO, though it does in NIST:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1911039/51559480-e5fdc380-1e79-11e9-9c1c-e2d904473787.png">

**Comment by opoudjis** [comment]
Inserting a continuation style paragraph into the `<div class="formula">` wrapper before formulae will take care of this. In fact, Math expressions should be wrapped in paragraphs for Word anyway: it's just safer.

**Comment by opoudjis** [comment]
Expanded https://github.com/riboseinc/isodoc/issues/73 to detect wrapper paragraphs within formulae, and indent them as well according to the surrounding list.
