### ISSUE TITLE
Table header styling (and figure caption styling) should follow original

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#28]
Original:
![screen shot 2019-01-08 at 6 58 57 am](https://user-images.githubusercontent.com/11865/50798302-e0996880-1312-11e9-989c-614d0167ae00.png)

Generated:
![screen shot 2019-01-08 at 6 59 29 am](https://user-images.githubusercontent.com/11865/50798327-f313a200-1312-11e9-8650-8fe846518c5b.png)

**Comment by ronaldtse** [comment]
This is from 800-126r3. The styling from 800-90B is different. I'm making a choice here.

The font-size should follow content font-size (i.e. 12pt).

**Comment by ronaldtse** [comment]
Figure caption fixed in 3491c6c42c38ba7984e413b21abe236da8b0dac0

**Comment by ronaldtse** [comment]
Table header styling (background, font style) still needs to get fixed.

**Comment by opoudjis** [comment]
Also center-aligning.
