### ISSUE TITLE
Make "Errata Table" a specialized element

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#3]
From JF:
> Errata Tables: I recommend encoding Errata Tables as specialized elements. The Errata are only included if the document is an Update (a modification of an existing publication, but not a full Revision). Errata table should be mandatory if the doc is an Update.

**Comment by opoudjis** [comment]
None of the sample documents contain one of these, though NIST.SP.800-126r3 contains an errata template.

**Comment by opoudjis** [comment]
I will treat the heading to the Errata section as boilerplate. I actually don't see real benefit to making it a specialised element: if JF is worried about conditional inclusion, that is a matter for sections, not for section headings. But I will proceed with it.

**Comment by opoudjis** [comment]
Actually, I won't treat the section header as boilerplate, because I don't know enough yet about how these will appear.
