### ISSUE TITLE
Render authorship and affiliation information

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#31]
Currently they're not rendered in Word, in the inner cover page. Left generated, right original.

<img width="1523" alt="screen shot 2019-01-09 at 12 54 10 am" src="https://user-images.githubusercontent.com/11865/50845997-1b4de000-13a9-11e9-891b-64b63db096e9.png">

**Comment by opoudjis** [comment]
Depends on https://github.com/riboseinc/metanorma-csd/issues/71
