### ISSUE TITLE
`:sectnums!:` not working for Executive Summary

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#34]
Input:

```adoc
:sectnums!:
[[a_1__Executive_Summary]]
== Executive Summary

The Security Content Automation Protocol (SCAP) is a suite of
```

Output:
<img width="314" alt="screen shot 2019-01-09 at 1 14 53 am" src="https://user-images.githubusercontent.com/11865/50847218-fb6beb80-13ab-11e9-84bd-5131ab162eac.png">

**Comment by opoudjis** [comment]
:sectnums!: is ignored in processing by metanorma, and should be. The Executive Summary should never be numbered. However, I cannot replicate this: my current version does not have any section numbering for Executive Summary in either Word or HTML output.

To ensure this behaviour, you must do something I've done in the source documents I've checked in, and you have failed to in the excerpt about: you must give the style attribute `[preface]` before the title, to all sections that will be unnumbered and in the document preface.

Please check out my versions of the Asciidoctor source for all documents.

**Comment by ronaldtse** [comment]
@opoudjis reopened because the Executive Summary is an actual section that shows up in the ToC. See 800-126r3.

**Comment by opoudjis** [comment]
Moved Executive Summary to appear in correct location.

The status of Executive Summary in ToC is unclear: one includes it, the other excludes it. I will include it, but this is the kind of maddening inconsistency that Metanorma will simply not support.

**Comment by ronaldtse** [comment]
Thanks, and agree. Either it is in the ToC or not.
