### ISSUE TITLE
Specialized element: chapter end notes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#35]
From #1 . @opoudjis do we have this?

**Comment by opoudjis** [comment]
No we do not yet.

**Comment by ronaldtse** [comment]
@opoudjis I don't have any examples of them; I will ask for this.

**Comment by ronaldtse** [comment]
@opoudjis apparently the only document in SP 800 series that uses this is SP 800-100:

https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-100.pdf

**Comment by ronaldtse** [comment]
Great news for you -- this element can be "legislated" out of existence. So closing it now!
