### ISSUE TITLE
Make gem release for metanorma-nist

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#36]
After these issues:

* [x] https://github.com/riboseinc/metanorma-nist/issues/34
* [x] https://github.com/riboseinc/metanorma-nist/issues/32
* [x] https://github.com/riboseinc/metanorma-nist/issues/14

If there is time,

* [ ] https://github.com/riboseinc/metanorma-nist/issues/31

**Comment by opoudjis** [comment]
#31 is tied up with a Metanorma-wide refactoring, and we're also undertaking a Metanorma-wide gem release. There will not be time.

**Comment by ronaldtse** [comment]
As long as this happens before mid next week, it’s good.
