### ISSUE TITLE
Exclude preface headings from ToC

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-nist#37]
To exclude preface headings from ToC systematically, will need to set the style for those headings not to h1, but to h1preface, similarly to h2Annex, so that they are not picked up in ToC indexing, in either Word or HTML.

Currently the Index works in HTML excluding those headings, but if the index is regenerated/updated (which is necessary for the right pages to show up), all the preface headings are inserted.

**Comment by ronaldtse** [comment]
I see! Thanks!

**Comment by ronaldtse** [comment]
@opoudjis will we get this fixed soon?

**Comment by opoudjis** [comment]
Fixed
