### ISSUE TITLE
Owner decisions to be made

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#39]
This is a running list for the owner of the documents.

* Terms and definitions
  * In ISO and others, each term has a clause number, can support notes, examples, alternative terms, sources. Right now in NIST SP 800 documents the terms are represented in a simplistic glossary.
  * The glossary in NIST SP 800 documents is placed in the Appendix. In other standard publications the terms and definitions section is usually a proper section.
  * Proposal: Make the glossary a full fledged terms section like the others.

* Bibliography
  * The bibliography in NIST SP 800 documents is placed into arbitrary appendixes (i.e. no specified order, e.g. first or last appendix).
  * The bibliography section is named arbitrarily amongst documents.
  * The bibliography better use a single structure across all documents, rather than have idiosyncratic strutures (tables).
  * Proposal: the bibliography should have a fixed position, fixed name, and use a uniform structure.

* Random italicized blocks (e.g. NIST SP 800-116r1 section 3)
  * These are not semantically motivated. They should be marked up as some sort of block.
  * Proposal: Use proper mark up (right now we mark them as IMPORTANT)

* Patent boilerplate
  * Need to know when this section should be included.
  * Proposal: Decide on whether a document attribute should include it, or on automatic detection.

* Footnotes in tables
  * In other formats, Footnotes inside tables are usually placed within the Table. In current documents they are made into footnotes of the document (fn in 126r3, Table 17).
  * Proposal: align with other international standards.

* Numbering of assets (tables, figures)
  * 800-116r1 is hierarchical
  * 800-126r3 is sequential (e.g. Table chapter-number vs table number)
  * Proposal: Decide on numbering: sequential numbering (ISO main body), or "{chapter}-{number within chapter}" (ISO Annex, hierarchical)

**Comment by opoudjis** [comment]
Note for Numbering of Assets: in fact ISO's usage is sequential, not hierarchical; I implemented hierarchical because it is distinctive to NIST.

**Comment by ronaldtse** [comment]
ISO figure numbering is hierarchical in Annexes, e.g. Figure B.3.

**Comment by opoudjis** [comment]
Yup. NIST is also hierarchical in the main body.

**Comment by ronaldtse** [comment]
Decisions received, split into separate issues:
* #43 
* #44 
* #45 
* #46 
* #47 
* #48 
* #49 
* #50 
* #51
