### ISSUE TITLE
Implement specialized Pseudocode block element

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#4]
From NIST SP 800-90B.

![nist-sp-800-90b-pseudocode-1](https://user-images.githubusercontent.com/11865/50128731-35683700-02b1-11e9-9818-82530756cfc5.png)

![nist-sp-800-90b-pseudocode-2](https://user-images.githubusercontent.com/11865/50128732-3600cd80-02b1-11e9-9c04-e17e927134f7.png)

**Comment by opoudjis** [comment]
The natural block to fit this under is `example`. I will in the first instance treat this as an example with the style attribute "pseudocode":

````
[pseudocode]
====
Input: ....
====
````

to be rendered as `<example type="pseudocode">`.

**Comment by ronaldtse** [comment]
Why do we encode this under `<example>`? This can be normative content. It should be of the same level as `<sourcecode>`?

**Comment by opoudjis** [comment]
It is decidedly not sourcecode in rendering terms, because it is full of formatting. Even if you insist on it being semantically sourcecode, it simply cannot be entered as an Asciidoc sourcecode block, or any other markup language's sourcecode block, because it is full of formatting.

**Comment by ronaldtse** [comment]
I'm not saying that this should be `<sourcecode>`, that would cause major confusion. How about it being semantically `<pseudocode>` or `<code type="pseudocode">`?

**Comment by opoudjis** [comment]
There's no real difference between `<sourcecode>` and `<code type="pseudocode">`. I think I'm being vague between how it is to be marked up in Asciidoc, and what the tag shall be in Metanorma XML. The former we are somewhat constrained, and using Asciidoc examples is the simplest thing. (Maybe blockquotes as well, but it doesn't actually make that much difference.)

As for the tag to be used in Metanorma XML, that is arbitrary, really, and I am not insisting on `<example>`. It could even be `<sourcecode type="pseudocode">` for all I care, or it could be `<pseudocode>`, though I'm reluctant to proliferate tags. I could use either; I take it you would much rather the latter?

**Comment by opoudjis** [comment]
In light of #25, where the captions are explicitly "Figure" in NIST, I am treating these as figures instead. I could make captions for examples, but they would then be labelled as "example"; that is clearly not the intent behind these documents.

**Comment by ronaldtse** [comment]
As mentioned in #25, pseudocode instances *could* specify _examples_ or actual _requirements_.

> The same applies to source code. It *could* be an example, or an actual requirement. The context we were given indicates that they don't need to be called "Figure".

What's the best way to deal with this here?

**Comment by ronaldtse** [comment]
Ping @opoudjis , need an answer for this 🙇

**Comment by opoudjis** [comment]
Oh god.

If they are a requirement, they should be marked up as a requirement: the fact there is pseudo code in there is incidental. In asciidoc, it would be an  example with style attribute "requirement", which happens to contain pseudo code.

I am not convinced that we actually know the intent here, and whether the grey box is about pseudo code, requirements, or figures. The documentation provided (hah) does not clarify this. But if we have already introduced markup of recommendations, we should treat requirements as a distinct category, whatever pseudo code they might contain.

**Comment by opoudjis** [comment]
And of course requirements need to be separately numbered. What they have currently with pseudo code markup is quite relaxed: it will not remain so.

**Comment by ronaldtse** [comment]
Ah, I had it mixed up. This is how pseudocode requirements can be marked up.

Requirement with pseudocode as example.
```
[requirement]
--
[pseudocode]
...
--
```

Requirement with pseudocode as machine-readable requirements:
```
[requirement,pseudocode-syntax]
--
...
--
```

**Comment by ronaldtse** [comment]
So right now, "pseudocode" is just another specialized "block element". There is no requirement intent attached.
