### ISSUE TITLE
Encode "Revision" concept

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#40]
NIST SP 800-126r3 has a "Revision 3"; SP 800-116r1 has a "Revision 1".

This text is supposed to show up on the cover page, and we also need to encode them in Metanorma XML.

**Comment by opoudjis** [comment]
That has already been done: I am using the `:draft:` variable, and have put `:draft: 1` and `:draft: 3` in the respective documents. The Word documents when last generated included that information successfully:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/1911039/51616502-231d9080-1f22-11e9-8cfc-41e5d2630985.png">

Could you please regenerate and confirm?

**Comment by opoudjis** [comment]
Would rather not proliferate tags, and I don't believe there is a real distinction between revision and edition. Using edition.

**Comment by opoudjis** [comment]
Changed documents in mn-nist-documents to match
