### ISSUE TITLE
Checklist items are normative "recommendations"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#43]
https://github.com/riboseinc/metanorma-nist/issues/39 1. Check list

From SP 800-81-2

Checklist:
* is a "recommendation"
* "normative"
* the single/double bordered styling is a formatting inconsistency.

Moreover, Section 7.4 aggregates the checklist items.

Double bordered check list item:
![image001](https://user-images.githubusercontent.com/11865/52159332-721ca180-2657-11e9-8d99-05f09a83be25.png)

Single bordered check list item:
![image002](https://user-images.githubusercontent.com/11865/52159329-6fba4780-2657-11e9-8339-5e0ec1d69c0e.png)

**Comment by opoudjis** [comment]
The only impact I can see this decision having is that Recommendations can optionally be called something other than Recommendations (such as "Checklists"). Frankly, I'd rather we not allow that kind of flexibility: it is confusing, and contradicts the imperative to make recommendations explicit in documents.

**Comment by ronaldtse** [comment]
True, let's keep it shown as a "recommendation". The border style is simply an inconsistently applied style, we don't need to do anything with it.

**Comment by opoudjis** [comment]
In that case, nothing more to do, so closing.
