### ISSUE TITLE
NIST bibliography: fixed location, uniform structure, separate informative/normative

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#47]
5. Bibliography
 
* The bibliography in NIST SP 800 documents is placed into arbitrary appendixes (i.e. no specified order, e.g. first or last appendix) and is named arbitrarily amongst documents.

  * Decision: We should make its location consistent. The NIST Library’s guidance is to place a section called “References” (with no section #) after the body of the document, immediately before the Appendices.
  * We (probably) should make its name consistent.

* The bibliography better use a single structure across all documents, rather than have idiosyncratic structures (tables).
  * Decision: It should have a uniform structure. 

* Proposal: the bibliography should have a fixed position, fixed name, and use a uniform structure.

* There should be separate normative/informative resources
  * Decision: If authors need to include other informative resources, such as websites or a bibliography of relevant material (but which is not referenced specifically within the document), then they can be included in an appendix.
  * Decision: A very small number of our publications have separate "normative" and "informative" bibliographies, and we should facilitate this behavior.

**Comment by opoudjis** [comment]
Because of the requirement for flexibility, there is no fixed name of the References section; there can be more than one.

Any bibliographies are now placed before the annex, and without a section number.

Informative resources are not bibliographies, and will not be treated as such.

**Comment by ronaldtse** [comment]
Just to clarify, we don’t need to have multiple references. There should only be one normative one and a bibliography (the informative one). 

It’s good if the references’ sections have configurable titles but they should not be arbitrary.

**Comment by opoudjis** [comment]
@ronaldtse The only way I think I can do this is to issue warnings; agreed?

**Comment by ronaldtse** [comment]
I'm confused -- what is the "warning" to be issued?

1. There is a clause on "Normative references" fixed after main content and before Appendixes.
2. If the author wants an "Informative references" section, it will be placed after the "Normative references" one.
3. If an author wants to change the name of item 1 or 2, give them a way to do so.

**Comment by opoudjis** [comment]
So, no warning if 2. The simplest way to do 3 is simply to permit arbitrary titles for references. Asciidoctor means the user will be supplying a title to the references no matter what; references will still be flagged as such with the `[bibliography]` style attribute.

**Comment by opoudjis** [comment]
... As far as I can tell, this means issuing a warning if there is more than one normative and one informative references section, and if the names are other than References, Bibliography.
