### ISSUE TITLE
Call for Patent Claims: ITL point of contact content should be flexible

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#48]
The ITL point of contact that’s to be inserted at the end of the "Call for Patent Claims" could include different information.

Not sure if we just want to have it as a freeform text field, since it could take a variety of forms (e.g., contact info for more than one person; email only; email and name; name, email and phone; etc.).

**Comment by opoudjis** [comment]
I am changing the value used for the point of contact from the email address for the document to a "patent-contact" attribute. I disagree that it should not be freeform text, especially given that this is being inserted into an HTML template to begin with.
