### ISSUE TITLE
Patent disclosure boilerplate: use document attribute

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#49]
The “Call for Patent Claims” and “Patent Disclosure Notice” boilerplates were recently added in response to a new internal policy that became effective January 1st. 

There should be a document attribute for including them, because the determination about whether they’re necessary will be based on a human decision rather than automatic detection.  

* If a draft contains guidance and/or requirements, then the "Call for Patent Claims" must be included. 

* The “Patent Disclosure Notice” section is only to be included in FINAL pubs whose draft included the Call for Patent Claims. Authors would need to select the appropriate option (and include ITL point of contact info for Option 1).

**Comment by opoudjis** [comment]
Added two document attributes to deal with this. ITL point of contact is based on doc-email. Adding boilerplate into XML preface.
