### ISSUE TITLE
Implement code block style

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#5]
From NIST SP 800-126R3. Notice that there are italics (!) within the second screenshot.

![nist-sp-800-126r3-code-1](https://user-images.githubusercontent.com/11865/50128752-516bd880-02b1-11e9-975c-b26a6398fb8a.png)

![nist-sp-800-126r3-code-2](https://user-images.githubusercontent.com/11865/50128751-516bd880-02b1-11e9-97f9-5a9e7b22f0d4.png)

**Comment by opoudjis** [comment]
Code is code, and it is not meant to have markup; Asciidoctor sourcecode is deliberately a pass-through. To render this in Asciidoctor, I will have to introduce markup and postprocess it. How about I introduce `{{{ ... }}}` as NIST-specific markup of variables (I think that's what these are supposed to be), which in post-processing will be changed to non-monospace?

**Comment by ronaldtse** [comment]
@opoudjis could we place this in StanDoc instead?

**Comment by opoudjis** [comment]
I dislike this functionality intensely, and would rather we keep it on a leash.

**Comment by ronaldtse** [comment]
OK we'll keep it here for now. I think the functionality was more meant as "emphasis" of code block elements. That said, Asciidoctor also supports referring back to code block lines, so it's not a simple pass-through?
