### ISSUE TITLE
Table footnotes: should be at end of Table

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#50]
In other formats, Footnotes inside tables are usually placed within the Table. In current documents they are made into footnotes of the document (fn in 126r3, Table 17).

Decisions:

* Footnotes in tables should be placed within the table (and use a, b, c, … lettering). 
* Other document footnotes should be numeric and appear at bottom of the page.

**Comment by opoudjis** [comment]
Had not implemented distinct table footnotes for NIST, so NIST gem is already following ISO practice.
