### ISSUE TITLE
Numbering of assets (tables, figures): follow ISO

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#51]
* 800-116r1 is hierarchical
* 800-126r3 is sequential (e.g. Table chapter-number vs table number)
* Proposal: Decide on numbering: sequential numbering (ISO main body), or "{chapter}-{number within chapter}" (ISO Annex, hierarchical)
 
Decision: Do it the same way as ISO:
* sequential in the main body
* "{chapter}-{number within chapter}” for the appendices (“Table A-1”)
* Same thing for Figures. 
* (this matches current desired practice)

**Comment by opoudjis** [comment]
Reverted hierarchical asset numbering within main body of document.
