### ISSUE TITLE
Implement Side Box specialized element

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#6]
Two types of side boxes from SP 800-81-2.

![nist-sp-800-81-2-box-1](https://user-images.githubusercontent.com/11865/50128778-72ccc480-02b1-11e9-9b50-f4dc25c6e8b8.png)

![nist-sp-800-81-2-box-2](https://user-images.githubusercontent.com/11865/50128777-72ccc480-02b1-11e9-85e0-5f3747bced19.png)

**Comment by opoudjis** [comment]
I have already repurposed the aside element for reviewer notes, and I do not wish to go back on that; so these will be implemented as admonitions.

**Comment by opoudjis** [comment]
Without any associated semantics, I am not going to implement a different rendering for these. We shall not be in the business of replicating purely decorative styling, and this needs to be made clear to NIST (as it should to all users of Metanorma). 

As far as I can tell, the box styling simply switches from checklist item 27 to 28, from 29 to 30, and 36 to 37, with no visible reason (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.391.104&rep=rep1&type=pdf). I will not be replicating that, nor should anyone. These will be simply IMPORTANT admonitions, unless I find a compelling reason to render them as something else.

**Comment by ronaldtse** [comment]
I have these points to offer:

1. A "check list" seems to me a normative element. In this case it should not be a NOTE. We need some way of representing this sort of thing.
2. The "side box" is a separate semantic element as requested by NIST that represents informative text. It is unclear whether the side box is normative or informative.
3. I agree we shouldn't implement differently styled elements, unless there is a semantic reason for doing so.

Thoughts?

**Comment by ronaldtse** [comment]
Simply reopening for comments.

**Comment by opoudjis** [comment]
If check list entries are semantically distinct, like recommendations and requirements, they should be expressly marked up as such; in fact, the check list seems to be just a variant of a requirement.

Admonitions are arguably already side boxes. In any case, Asciidoctor asides are simply not available to be used. And these check list entries are definitely not asides semantically: they are not digressive text, which is what "side boxes" are supposed to be. Boxes that are not asides but are integrated into the text and normative -- that *is* what admonitions are.

Until I see an actual style guide out of NIST that says what side boxes are for (and that they are used for something other than check list entries), I will not guess that they are anything different from IMPORTANT admonitions. If you know that they represent informative text, you know more than I do, and you need to provide me with your source of information.

**Comment by ronaldtse** [comment]
But the point is, there is something called a "side box" that needs to be semantically separate. I imagine that this is already done as an Admonition? If that's the case we're good here.

**Comment by opoudjis** [comment]
In my opinion, that is what I've been nations are. There is a semantic distinction, I guess, between asides and admonitions, in that asides are completely digressive and are not part of the narrative, whereas admonitions highlight something you need to be aware of, like a tip, and are part of the narrative. But the checklist entries are definitely in that case admonitions rather than asides.

**Comment by ronaldtse** [comment]
I actually think the checklist is a different semantic element. A checklist should actually be placed by itself, and after the paragraph that describes a checklist item, it should refer back to the specific item in the checklist. 

Asides/Side boxes are purely informative. Admonitions may or may not be normative, but they are not part of the actual content. 

A checklist however, can be actual content, and seems closer to a “requirement”?

**Comment by opoudjis** [comment]
In that case, checklists *are* requirements. If you want to reopen this issue, go ahead. Be prepared for a very long wait, unless you can get NIST to commit a developer: there are a lot of higher priority issues.
