### ISSUE TITLE
Encoding a machine-readable example

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#7]
> We want to be able to semantically tag our content to uniquely identify requirements, recommendations, permissible (“may”) elements, etc.  Since we have a number of validation programs (e.g., SCAP, PIV, CAVP), being able to link to requirements directly from our validation testing pubs and tools would be great.
 
> In our pubs, these are sometimes separated from the content (e.g., 116R1) so that they are more easily human-readable, while most pubs indicate them as part of the narrative.

> To represent various configurations of requirement/recommendation (that are sometimes nested) and their dependencies  E.g., see Sec. 3.1.2 (p.11) of 800-90B:
> 
> “The track selection is done based on the following rules. The IID track shall be used only when all of the following conditions are satisfied:
> 1. The submitter makes an IID claim on the noise source, based on the submitter’s analysis of the design. The submitter shall provide rationale for the IID claim.
> 2. The sequential dataset described in item 1 of Section 3.1.1 is tested using the statistical tests described in Section 5 to verify the IID assumption, and the IID assumption is verified (i.e., there is no evidence that the data is not IID).
> 3. The row and column datasets described in item 3 of Section 3.1.1 are tested using the statistical tests described in Section 5 to verify the IID assumption, and the IID assumption is verified.”

**Comment by opoudjis** [comment]
There is of course absolutely no way this will be done in time for the 15th. I'm not convinced this will even be done in time for the 25th, which is when you're talking to ISO about machine readable requirements.

**Comment by opoudjis** [comment]
Should follow from https://github.com/riboseinc/metanorma-standoc/issues/34

**Comment by opoudjis** [comment]
I have *an* encoding now under https://github.com/riboseinc/metanorma-standoc/issues/34; I am assuming that is the basis for further work.

... It had better be >:-(

**Comment by opoudjis** [comment]
Moving this to https://github.com/riboseinc/metanorma-ogc/issues/20, because it is dumb for this discussion to be split across three tickets.

**Comment by ronaldtse** [comment]
@opoudjis indeed we will merge all discussions there. 👍
