### ISSUE TITLE
Namespace of NIST documents

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-nist#8]
I think we should do something like this:

```xml
<metanorma-standard>
  <nist xmlns="https://www.nist.gov/xml/metanorma">
   ...
  </nist>
</metanorma-standard>
```

Thoughts?

**Comment by opoudjis** [comment]
Thoughts: (a) no (b) STOP TINKERING AND LET ME FINISH SOMETHING (b) what on earth is this supposed to gain? (d) no.

**Comment by opoudjis** [comment]
The namespace has been changed to http://www.nist.gov/metanorma.
